Week6Capstone/Models/Task.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week6Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Status { get; set; }
        public int UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}

Week6Capstone/Models/User.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week6Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
    }
}

Week6Capstone/Models/UserTaskListDB.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week6Capstone.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UserTaskListDBEntities : DbContext
    {
        public UserTaskListDBEntities()
            : base("name=UserTaskListDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}

Week6Capstone/Models/UserTaskListDB.Designer.cs
// T4 code generation is enabled for model 'F:\GrandCircus\Documents\Capstones\Week6Capstone\Week6Capstone\Models\UserTaskListDB.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

Week6Capstone/Models/UserTaskListDB.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

Week6Capstone/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Week6Capstone.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

Week6Capstone/Controllers/UserTaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Week6Capstone.Models;

namespace Week6Capstone.Controllers
{
    public class UserTaskController : Controller
    {
        UserTaskListDBEntities ORM = new UserTaskListDBEntities();
        

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CreateUser()
        {
            return View();
        }

        public ActionResult SaveNewUser(User newUser)
        {
            if (ModelState.IsValid)
            {
                ORM.Users.Add(newUser);
                ORM.SaveChanges();
                return RedirectToAction("../Home/Index");
            }
            else
            {
                ViewBag.ErrorMessage = "Something didn't go right..";
                return View("CreateUser");
            }
        }

        public ActionResult Login()
        {
            return View();
        }

        public ActionResult UserPage(User loginUser)
        {
            if(Session["CurrentUser"] != null)
            {
                return View();
            }

            List<User> userList = ORM.Users.ToList();

            User user = userList.Find(u => u.Email == loginUser.Email);

            if(user != null)
            {
                if (loginUser.Password == user.Password)
                {
                    loginUser.Id = user.Id;
                    Session["CurrentUser"] = loginUser;
                    return View();
                }
                else
                {
                    ViewBag.ErrorMessage = "Email or Password was incorrect...";
                    return RedirectToAction("Login");
                }
            }
            
            ViewBag.ErrorMessage = "There are no users with this email address..";
            return RedirectToAction("Login");
        }

        public ActionResult TaskList()
        {
            User user = (User)Session["CurrentUser"];

            ViewBag.taskList = ORM.Tasks.ToList().FindAll(t => t.UserID == user.Id).ToList();

            return View();
        }
        public ActionResult AddTask(Task newTask)
        {
            User user = (User)Session["CurrentUser"];

            if (ModelState.IsValid)
            {
                newTask.UserID = user.Id;
                ORM.Tasks.Add(newTask);
                ORM.SaveChanges();
                return RedirectToAction("TaskList");
            }
            else
            {
                ViewBag.ErrorMessage = "Something didn't go right..";
                return View("TaskForm");
            }
        }

        public ActionResult TaskForm()
        {
            return View();
        }

        public ActionResult DeleteTask(int TaskID)
        {
            
            Task found = ORM.Tasks.Find(TaskID);
            ORM.Tasks.Remove(found);
            ORM.SaveChanges();
            return RedirectToAction("TaskList");
        }

        public ActionResult UpdateTask(int TaskID)
        {

            ORM.Tasks.Find(TaskID).Status = "True";
            ORM.SaveChanges();
            return RedirectToAction("TaskList");
        }

        public ActionResult Logout()
        {
            Session.Remove("CurrentUser");
            return RedirectToAction("../Home/Index");
        }
    }
}

Week6Capstone/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<a href="../UserTask/CreateUser">Create Account!</a>

@if (Session["CurrentUser"] != null)
{
    <a href="../UserTask/Logout" class="btn-danger">Logout</a>

}
else
{
    <a href="../UserTask/Login">Login!</a>
}

Week6Capstone/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @if (Session["CurrentUser"] != null)
                    {
                    <li>@Html.ActionLink("UserPage", "UserPage", "UserTask")</li>
                    }
                    
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Week6Capstone/Views/UserTask/CreateUser.cshtml
@{
    ViewBag.Title = "CreateUser";
}

<h2>CreateUser</h2>

<form action="../UserTask/SaveNewUser" method="post">

    <input type="email" name="Email" placeholder="Email" required />
    <input type="password" name="Password" placeholder="Password" required />

    <input type="submit" value="Submit" class="btn-success" />
</form>

<h3>@ViewBag.ErrorMessage</h3>

Week6Capstone/Views/UserTask/Login.cshtml
@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>



<form action="../UserTask/UserPage" method="post">
    
    
    <input type="email" name="Email" placeholder="Email" required />
    <input type="password" name="Password" placeholder="Password" required />

    <input type="submit" class="btn-success" />
</form>

<h3>@ViewBag.ErrorMessage</h3>

Week6Capstone/Views/UserTask/TaskForm.cshtml
@{
    ViewBag.Title = "TaskForm";
}
<h2>TaskForm</h2>

<h2>Add a new Task Here!</h2>

<form action="../UserTask/AddTask" method="post">
    
    <input type="text" name="Description" placeholder="Description" />
    <input type="date" name="DueDate" placeholder="YYYY-MM-DD" />
    <input type="hidden" name="Status" value="False" />

    <input type="submit" value="Add new Task!" class="btn-success" />
</form>

<p class="danger">@ViewBag.ErrorMessage</p>

Week6Capstone/Views/UserTask/TaskList.cshtml
@{
    ViewBag.Title = "TaskList";
}

<h2>TaskList</h2>
<a href="../UserTask/TaskForm">Add a Task!</a>
<a href="../UserTask/Logout" class="btn-danger">Logout</a>

<table class="table">
    <tr>
        <th>Description</th>
        <th>Due Date</th>
        <th>Competion Status</th>
    </tr>
    @foreach (var task in @ViewBag.taskList)
    {
        <tr>
            <td id="description">@task.Description</td>
            <td id="dueDate">@task.DueDate.ToShortDateString()</td>
            <td id="status">@task.Status</td>
            <td>
                <a href="../UserTask/UpdateTask?TaskID=@task.Id" class="btn-primary">Update</a>
                <a href="../UserTask/DeleteTask?TaskID=@task.Id" class="btn-danger">Delete</a>
            </td>
        </tr>
    }
</table>

Week6Capstone/Views/UserTask/UserPage.cshtml
@{
    ViewBag.Title = "UserPage";
}

<h2>UserPage</h2>

<a href="../UserTask/TaskList" class="btn-success">View your Tasks!</a>
<a href="../UserTask/Logout" class="btn-danger">Logout</a>